export const bookdata = [
    {
      image:
        "https://marketplace.canva.com/EAFaQMYuZbo/1/0/1003w/canva-brown-rusty-mystery-novel-book-cover-hG1QhA7BiBU.jpg",
      title: "The Art of Programming",
      ratings: 2.3,
      price: 704.38,
      author: "John Smith",
      genre: "College",
      publication_date: "12/17/1940",
      isbn: "330553211-4",
      publisher: "Random House",
      page_count: 1477,
      language: "Tajik",
      format: "paperback",
    },
    {
      image:
        "https://marketplace.canva.com/EAFaQMYuZbo/1/0/1003w/canva-brown-rusty-mystery-novel-book-cover-hG1QhA7BiBU.jpg",
      title: "Mastering Algorithms",
      ratings: 3.2,
      price: 149.24,
      author: "Jane Doe",
      genre: "College",
      publication_date: "4/3/1940",
      isbn: "613920436-4",
      publisher: "Oxford University Press",
      page_count: 285,
      language: "Filipino",
      format: "hardcover",
    },
    {
      image:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQaazkJXb4lvzbCxKV6A5Vz6xBl-raDRkiKpXPPRaPYzO9Qqk-ySg-gIdGpWluu1P5_-h0&usqp=CAU",
      title: "Web Development Essentials",
      ratings: 1.2,
      price: 971.25,
      author: "Alex Johnson",
      genre: "Technical",
      publication_date: "7/10/1987",
      isbn: "380631981-2",
      publisher: "Bloomsbury Publishing",
      page_count: 1342,
      language: "Persian",
      format: "ebook",
    },
    {
      image:
        "https://marketplace.canva.com/EAFfSnGl7II/2/0/1003w/canva-elegant-dark-woods-fantasy-photo-book-cover-vAt8PH1CmqQ.jpg",
      title: "Data Science Handbook",
      ratings: 4.6,
      price: 123.71,
      author: "Emily Brown",
      genre: "Technical",
      publication_date: "6/24/2001",
      isbn: "616000383-6",
      publisher: "Simon & Schuster",
      page_count: 1389,
      language: "Georgian",
      format: "ebook",
    },
    {
      image:
        "https://marketplace.canva.com/EAFfSnGl7II/2/0/1003w/canva-elegant-dark-woods-fantasy-photo-book-cover-vAt8PH1CmqQ.jpg",
      title: "Cybersecurity Fundamentals",
      ratings: 2.9,
      price: 963.89,
      author: "Michael Lee",
      genre: "Finance",
      publication_date: "12/6/1905",
      isbn: "833462921-4",
      publisher: "Penguin Random House",
      page_count: 438,
      language: "Arabic",
      format: "paperback",
    },
    {
      image:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQaazkJXb4lvzbCxKV6A5Vz6xBl-raDRkiKpXPPRaPYzO9Qqk-ySg-gIdGpWluu1P5_-h0&usqp=CAU",
      title: "The Intelligent Investor",
      ratings: 1.8,
      price: 353.0,
      author: "Robert Kiyosaki",
      genre: "Non-Technical",
      publication_date: "9/23/1917",
      isbn: "957196629-0",
      publisher: "Oxford University Press",
      page_count: 1202,
      language: "Swahili",
      format: "paperback",
    },
    {
      image:
        "https://marketplace.canva.com/EAFaQMYuZbo/1/0/1003w/canva-brown-rusty-mystery-novel-book-cover-hG1QhA7BiBU.jpg",
      title: "Rich Dad Poor Dad",
      ratings: 2.1,
      price: 620.29,
      author: "Suze Orman",
      genre: "Technical",
      publication_date: "10/5/1959",
      isbn: "829643746-5",
      publisher: "Simon & Schuster",
      page_count: 643,
      language: "Finnish",
      format: "hardcover",
    },
    {
      image:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQaazkJXb4lvzbCxKV6A5Vz6xBl-raDRkiKpXPPRaPYzO9Qqk-ySg-gIdGpWluu1P5_-h0&usqp=CAU",
      title: "Think and Grow Rich",
      ratings: 2.4,
      price: 80.21,
      author: "Dave Ramsey",
      genre: "Motivation",
      publication_date: "12/4/1994",
      isbn: "511142774-0",
      publisher: "Macmillan Publishers",
      page_count: 125,
      language: "Assamese",
      format: "ebook",
    },
    {
      image:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQaazkJXb4lvzbCxKV6A5Vz6xBl-raDRkiKpXPPRaPYzO9Qqk-ySg-gIdGpWluu1P5_-h0&usqp=CAU",
      title: "The Millionaire Next Door",
      ratings: 4.9,
      price: 561.78,
      author: "Tony Robbins",
      genre: "Motivation",
      publication_date: "2/4/1946",
      isbn: "359700208-0",
      publisher: "Macmillan Publishers",
      page_count: 1272,
      language: "Portuguese",
      format: "paperback",
    },
    {
      image:
        "https://marketplace.canva.com/EAFaQMYuZbo/1/0/1003w/canva-brown-rusty-mystery-novel-book-cover-hG1QhA7BiBU.jpg",
      title: "The Total Money Makeover",
      ratings: 3.9,
      price: 56.95,
      author: "Napoleon Hill",
      genre: "Non-Technical",
      publication_date: "2/8/1960",
      isbn: "995890780-1",
      publisher: "Oxford University Press",
      page_count: 1151,
      language: "Telugu",
      format: "paperback",
    },
    {
      image:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQaazkJXb4lvzbCxKV6A5Vz6xBl-raDRkiKpXPPRaPYzO9Qqk-ySg-gIdGpWluu1P5_-h0&usqp=CAU",
      title: "Mathematics 101",
      ratings: 4.8,
      price: 171.01,
      author: "Mark Twain",
      genre: "Motivation",
      publication_date: "2/19/1948",
      isbn: "883719953-8",
      publisher: "Simon & Schuster",
      page_count: 1278,
      language: "Swahili",
      format: "ebook",
    },
    {
      image:
        "https://marketplace.canva.com/EAFaQMYuZbo/1/0/1003w/canva-brown-rusty-mystery-novel-book-cover-hG1QhA7BiBU.jpg",
      title: "Literature Classics",
      ratings: 1.2,
      price: 10.79,
      author: "J.K. Rowling",
      genre: "School",
      publication_date: "3/30/1902",
      isbn: "956062757-0",
      publisher: "HarperCollins",
      page_count: 90,
      language: "Hungarian",
      format: "hardcover",
    },
    {
      image:
        "https://marketplace.canva.com/EAFfSnGl7II/2/0/1003w/canva-elegant-dark-woods-fantasy-photo-book-cover-vAt8PH1CmqQ.jpg",
      title: "History of World Wars",
      ratings: 3.7,
      price: 263.21,
      author: "Roald Dahl",
      genre: "College",
      publication_date: "12/29/1976",
      isbn: "719826064-0",
      publisher: "Oxford University Press",
      page_count: 1355,
      language: "Punjabi",
      format: "ebook",
    },
    {
      image:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQaazkJXb4lvzbCxKV6A5Vz6xBl-raDRkiKpXPPRaPYzO9Qqk-ySg-gIdGpWluu1P5_-h0&usqp=CAU",
      title: "Science Explorations",
      ratings: 2.9,
      price: 836.38,
      author: "Dr. Seuss",
      genre: "College",
      publication_date: "12/9/1953",
      isbn: "171745006-7",
      publisher: "Penguin Random House",
      page_count: 1406,
      language: "Yiddish",
      format: "ebook",
    },
    {
      image:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQaazkJXb4lvzbCxKV6A5Vz6xBl-raDRkiKpXPPRaPYzO9Qqk-ySg-gIdGpWluu1P5_-h0&usqp=CAU",
      title: "Art and Creativity",
      ratings: 2.0,
      price: 532.37,
      author: "Shel Silverstein",
      genre: "Finance",
      publication_date: "11/25/2002",
      isbn: "237840994-X",
      publisher: "Macmillan Publishers",
      page_count: 240,
      language: "Croatian",
      format: "ebook",
    },
    {
      image:
        "https://marketplace.canva.com/EAFfSnGl7II/2/0/1003w/canva-elegant-dark-woods-fantasy-photo-book-cover-vAt8PH1CmqQ.jpg",
      title: "Introduction to Biology",
      ratings: 5.0,
      price: 576.55,
      author: "Stephen King",
      genre: "School",
      publication_date: "3/12/1957",
      isbn: "000138074-5",
      publisher: "Simon & Schuster",
      page_count: 66,
      language: "Icelandic",
      format: "hardcover",
    },
    {
      image:
        "https://marketplace.canva.com/EAFfSnGl7II/2/0/1003w/canva-elegant-dark-woods-fantasy-photo-book-cover-vAt8PH1CmqQ.jpg",
      title: "Calculus for Beginners",
      ratings: 2.3,
      price: 543.26,
      author: "George Orwell",
      genre: "School",
      publication_date: "2/9/1952",
      isbn: "799722472-6",
      publisher: "Oxford University Press",
      page_count: 140,
      language: "Lithuanian",
      format: "paperback",
    },
    {
      image:
        "https://marketplace.canva.com/EAFaQMYuZbo/1/0/1003w/canva-brown-rusty-mystery-novel-book-cover-hG1QhA7BiBU.jpg",
      title: "History of Art",
      ratings: 3.3,
      price: 606.39,
      author: "Harper Lee",
      genre: "College",
      publication_date: "3/29/1959",
      isbn: "006250041-4",
      publisher: "Penguin Books",
      page_count: 39,
      language: "Spanish",
      format: "hardcover",
    },
    {
      image:
        "https://marketplace.canva.com/EAFaQMYuZbo/1/0/1003w/canva-brown-rusty-mystery-novel-book-cover-hG1QhA7BiBU.jpg",
      title: "Chemistry Fundamentals",
      ratings: 4.9,
      price: 381.74,
      author: "J.R.R. Tolkien",
      genre: "Technical",
      publication_date: "11/18/1944",
      isbn: "075949845-8",
      publisher: "HarperCollins",
      page_count: 643,
      language: "Macedonian",
      format: "ebook",
    },
    {
      image:
        "https://marketplace.canva.com/EAFfSnGl7II/2/0/1003w/canva-elegant-dark-woods-fantasy-photo-book-cover-vAt8PH1CmqQ.jpg",
      title: "Literature Analysis",
      ratings: 1.7,
      price: 539.44,
      author: "Tony Robbins",
      genre: "Finance",
      publication_date: "8/17/2018",
      isbn: "280887588-6",
      publisher: "Macmillan Publishers",
      page_count: 748,
      language: "Armenian",
      format: "paperback",
    },
    {
      image:
        "https://marketplace.canva.com/EAFfSnGl7II/2/0/1003w/canva-elegant-dark-woods-fantasy-photo-book-cover-vAt8PH1CmqQ.jpg",
      title: "The Power of Now",
      ratings: 2.4,
      price: 309.57,
      author: "Brene Brown",
      genre: "Motivation",
      publication_date: "6/9/1933",
      isbn: "753894640-3",
      publisher: "Penguin Books",
      page_count: 35,
      language: "Dhivehi",
      format: "paperback",
    },
    {
      image:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQaazkJXb4lvzbCxKV6A5Vz6xBl-raDRkiKpXPPRaPYzO9Qqk-ySg-gIdGpWluu1P5_-h0&usqp=CAU",
      title: "Atomic Habits",
      ratings: 1.5,
      price: 211.22,
      author: "Dale Carnegie",
      genre: "Finance",
      publication_date: "6/12/1994",
      isbn: "486281950-8",
      publisher: "Oxford University Press",
      page_count: 718,
      language: "Korean",
      format: "ebook",
    },
    {
      image:
        "https://marketplace.canva.com/EAFaQMYuZbo/1/0/1003w/canva-brown-rusty-mystery-novel-book-cover-hG1QhA7BiBU.jpg",
      title: "Mindset: The New Psychology of Success",
      ratings: 1.9,
      price: 812.22,
      author: "Zig Ziglar",
      genre: "School",
      publication_date: "11/29/2014",
      isbn: "613221300-7",
      publisher: "Macmillan Publishers",
      page_count: 858,
      language: "Assamese",
      format: "ebook",
    },
    {
      image:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQaazkJXb4lvzbCxKV6A5Vz6xBl-raDRkiKpXPPRaPYzO9Qqk-ySg-gIdGpWluu1P5_-h0&usqp=CAU",
      title: "The 7 Habits of Highly Effective People",
      ratings: 1.2,
      price: 194.4,
      author: "Napoleon Hill",
      genre: "Motivation",
      publication_date: "8/10/1904",
      isbn: "998104926-3",
      publisher: "Random House",
      page_count: 520,
      language: "Hungarian",
      format: "hardcover",
    },
    {
      image:
        "https://marketplace.canva.com/EAFfSnGl7II/2/0/1003w/canva-elegant-dark-woods-fantasy-photo-book-cover-vAt8PH1CmqQ.jpg",
      title: "Grit: The Power of Passion and Perseverance",
      ratings: 4.8,
      price: 922.74,
      author: "John Smith",
      genre: "Finance",
      publication_date: "11/24/1931",
      isbn: "985060714-9",
      publisher: "Macmillan Publishers",
      page_count: 31,
      language: "Kannada",
      format: "hardcover",
    },
    {
      image:
        "https://marketplace.canva.com/EAFaQMYuZbo/1/0/1003w/canva-brown-rusty-mystery-novel-book-cover-hG1QhA7BiBU.jpg",
      title: "The Art of Programming",
      ratings: 1.4,
      price: 447.71,
      author: "Jane Doe",
      genre: "Finance",
      publication_date: "6/28/1905",
      isbn: "389453947-X",
      publisher: "Random House",
      page_count: 1007,
      language: "Malayalam",
      format: "hardcover",
    },
    {
      image:
        "https://marketplace.canva.com/EAFfSnGl7II/2/0/1003w/canva-elegant-dark-woods-fantasy-photo-book-cover-vAt8PH1CmqQ.jpg",
      title: "Mastering Algorithms",
      ratings: 3.4,
      price: 676.07,
      author: "Alex Johnson",
      genre: "Non-Technical",
      publication_date: "9/19/1947",
      isbn: "126362101-5",
      publisher: "Hachette Book Group",
      page_count: 1132,
      language: "Hebrew",
      format: "hardcover",
    },
    {
      image:
        "https://marketplace.canva.com/EAFaQMYuZbo/1/0/1003w/canva-brown-rusty-mystery-novel-book-cover-hG1QhA7BiBU.jpg",
      title: "Web Development Essentials",
      ratings: 4.7,
      price: 337.65,
      author: "Emily Brown",
      genre: "School",
      publication_date: "12/29/1973",
      isbn: "471755862-6",
      publisher: "HarperCollins",
      page_count: 370,
      language: "Danish",
      format: "paperback",
    },
    {
      image:
        "https://marketplace.canva.com/EAFaQMYuZbo/1/0/1003w/canva-brown-rusty-mystery-novel-book-cover-hG1QhA7BiBU.jpg",
      title: "Data Science Handbook",
      ratings: 3.2,
      price: 826.64,
      author: "Michael Lee",
      genre: "College",
      publication_date: "10/24/1962",
      isbn: "821668276-X",
      publisher: "HarperCollins",
      page_count: 627,
      language: "Lithuanian",
      format: "paperback",
    },
    {
      image:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQaazkJXb4lvzbCxKV6A5Vz6xBl-raDRkiKpXPPRaPYzO9Qqk-ySg-gIdGpWluu1P5_-h0&usqp=CAU",
      title: "Cybersecurity Fundamentals",
      ratings: 4.0,
      price: 894.52,
      author: "Robert Kiyosaki",
      genre: "College",
      publication_date: "7/24/1985",
      isbn: "339488912-9",
      publisher: "Simon & Schuster",
      page_count: 120,
      language: "Ndebele",
      format: "ebook",
    },
  ];
  