export const ourcoursedata = [
  {
    image: "images/course.jpg",
    title: "Computer Science Fundamentals",
    subject: "App development",
    course_type: "true",
    price: 793.26,
    course_level: "Advanced Level",
    content_duration: "3 hours",
  },
  {
    image: "images/course.jpg",
    title: "History of Art",
    subject: "App development",
    course_type: "true",
    price: 284.62,
    course_level: "Advanced Level",
    content_duration: "45 minutes",
  },
  {
    image: "images/course.jpg",
    title: "Introduction to Biology",
    subject: "Web development",
    course_type: "true",
    price: 978.54,
    course_level: "Advanced Level",
    content_duration: "1 hour",
  },
  {
    image: "images/course.jpg",
    title: "Computer Science Fundamentals",
    subject: "Business Finance",
    course_type: "true",
    price: 141.03,
    course_level: "Intermediate Level",
    content_duration: "30 minutes",
  },
  {
    image: "images/course.jpg",
    title: "History of Art",
    subject: "Business Finance",
    course_type: "true",
    price: 430.99,
    course_level: "Intermediate Level",
    content_duration: "2 hours",
  },
  {
    image: "images/course.jpg",
    title: "Introduction to Biology",
    subject: "Business Finance",
    course_type: "true",
    price: 473.77,
    course_level: "Beginner Level",
    content_duration: "30 minutes",
  },
  {
    image: "images/course.jpg",
    title: "Statistics for Business",
    subject: "App development",
    course_type: "false",
    price: 638.26,
    course_level: "Intermediate Level",
    content_duration: "2 hours",
  },
  {
    image: "images/course.jpg",
    title: "Introduction to Biology",
    subject: "DSA",
    course_type: "false",
    price: 950.87,
    course_level: "All Levels",
    content_duration: "45 minutes",
  },
  {
    image: "images/course.jpg",
    title: "History of Art",
    subject: "DSA",
    course_type: "true",
    price: 97.59,
    course_level: "All Levels",
    content_duration: "30 minutes",
  },
  {
    image: "images/course.jpg",
    title: "Computer Science Fundamentals",
    subject: "Web development",
    course_type: "false",
    price: 528.68,
    course_level: "All Levels",
    content_duration: "2 hours",
  },
  {
    image: "images/course.jpg",
    title: "Computer Science Fundamentals",
    subject: "App development",
    course_type: "true",
    price: 191.45,
    course_level: "All Levels",
    content_duration: "3 hours",
  },
  {
    image: "images/course.jpg",
    title: "Statistics for Business",
    subject: "Web development",
    course_type: "true",
    price: 635.93,
    course_level: "Intermediate Level",
    content_duration: "1 hour",
  },
  {
    image: "images/course.jpg",
    title: "History of Art",
    subject: "Business Finance",
    course_type: "true",
    price: 407.93,
    course_level: "Intermediate Level",
    content_duration: "1 hour",
  },
  {
    image: "images/course.jpg",
    title: "Creative Writing Workshop",
    subject: "App development",
    course_type: "true",
    price: 612.2,
    course_level: "Intermediate Level",
    content_duration: "2 hours",
  },
  {
    image: "images/course.jpg",
    title: "Creative Writing Workshop",
    subject: "DSA",
    course_type: "false",
    price: 613.05,
    course_level: "Advanced Level",
    content_duration: "1 hour",
  },
  {
    image: "images/course.jpg",
    title: "Computer Science Fundamentals",
    subject: "Web development",
    course_type: "false",
    price: 110.02,
    course_level: "Intermediate Level",
    content_duration: "2 hours",
  },
  {
    image: "images/course.jpg",
    title: "History of Art",
    subject: "Web development",
    course_type: "true",
    price: 758.79,
    course_level: "Intermediate Level",
    content_duration: "3 hours",
  },
  {
    image: "images/course.jpg",
    title: "Computer Science Fundamentals",
    subject: "App development",
    course_type: "false",
    price: 295.54,
    course_level: "Beginner Level",
    content_duration: "1 hour",
  },
  {
    image: "images/course.jpg",
    title: "Statistics for Business",
    subject: "DSA",
    course_type: "true",
    price: 42.66,
    course_level: "Intermediate Level",
    content_duration: "3 hours",
  },
  {
    image: "images/course.jpg",
    title: "Introduction to Biology",
    subject: "Business Finance",
    course_type: "false",
    price: 136.48,
    course_level: "Intermediate Level",
    content_duration: "3 hours",
  },
];
