import { Button } from "./Button";
import { Img } from "./Img";
import { Text } from "./Text";
import { Heading } from "./Heading";
import { RatingBar } from "./RatingBar";
import { Input } from "./Input";
import { Slider } from "./Slider";
import { CheckBox } from "./CheckBox";
import { SelectBox } from "./SelectBox";
export { Button, Img, Text, Heading, RatingBar, Input, Slider, CheckBox, SelectBox };
